version: '3.7'

networks:
  adaptor-net:
    external: true

services:

  jobmanager:
    build: 
      dockerfile: ./Dockerfile114
      context: .
    hostname: jobmanager
    ports:
      - 8081:8081
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - adaptor-net
    command: "jobmanager"
    env_file:
      - ./env
    volumes:
      - jars:/jars/flink-web-upload
    restart: always


  taskmanager:
    build: 
      dockerfile: ./Dockerfile114
      context: .
    hostname: taskmanager
    env_file:
      - ./env
    environment:
      - "TZ=Asia/Kolkata"
    networks:
      - adaptor-net
    command: "jobmanager"
    restart: always

volumes:
  jars:
