apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver-deployment
  labels:
    app: mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
        - name: mockserver
          image: iudx/adaptor-mockserver:latest
          imagePullPolicy: Never
          command: [ "java" ]
          args: [ "-jar", "mockserver/target/mockserver.jar" ]
          ports:
            - containerPort: 8080
