apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: mockserver
spec:
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080 
      nodePort: 30001

  selector:
    # Looks for labels `app:minio1` in the namespace and applies the spec
    app: mockserver
