apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-06-17T00-10-46Z
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"
#      containers:
#        - name: nginx
#          image: nginx:1.14.2
#          ports:
#            - containerPort: 80
#      volumes:
#        - name: nginx-conf-volume
#          hostPath:
#            path: /data

